
strings = [
  ("pcamp_thanks_help", "Thanks for help against these bastards."),
  ("pcamp_unexpected_context", "Why, this was an unexpected meeting! (debug context {reg0})."),
  ("pcamp_can_accomodate_all_reg2", "Your party can accomodate all {reg2} of our troops."),
  ("pcamp_can_accomodate_reg0_of_reg2", "Your party can accomodate {reg0} out of {reg2} troops."),
  ("pcamp_can_accomodate_none_of_reg2", "Your party can't even accomodate myself, let alone {reg2} men."),
  ("pcamp_no_prisoners", "We have no prisoners in camp."),
  ("pcamp_can_keep_all_reg3_prisoners", "We can keep all {reg3} prisoners."),
  ("pcamp_can_keep_reg1_of_reg3_prisoners", "We can keep {reg1} out of {reg3} prisoners."),
  ("pcamp_can_keep_none_of_reg3_prisoners", "We'll have to release all {reg3} prisoners."),
  ("pcamp_disband_leave", "we still disband and you can have a few days leave"),
  ("pcamp_disband_one", "we will take you and disband the rest"),
  ("pcamp_disband_top_reg0", "we will take {reg0} top people and disband the rest"),
  ("pcamp_disband_max_prisoners", "we will just take as many prisoners as we can"),
  ("pcamp_acting_as_commander", "Acting as a camp commander"),
  ("pcamp_near_s9", "near {s9}"),
  ("pcamp_too_many_camps", "You already have too many active permanent camps."),
  ("pcamp_no_free_companions", "You don't have any companions available to command a permanent camp."),
  ("pcamp_no_reg7_denars", "You don't have {reg7} denars needed to start a permanent camp."),
  ("pcamp_too_far_from_s0", "You are too far from {s0} for the camp to supply itself."),
  ("pcamp_can_start_camp_s0_reg5_reg6_reg7", "You can leave a companion to manage a camp near {s0} with a part of your troops until you return. He will require {reg7} denars for initial expenses.^^You can create {reg5} more camps and have {reg6} denars available."),
  ("pcamp_s0_destroyed", "{s0} has been destroyed!"),
  ("pcamp_is_commanding_near_s5", "Is commanding a camp near {s5}."),
  ("pcamp_s0s_camp", "{s0}'s Camp"),
  ("pcamp_soldiers_from_s3", "soldiers from {s3}"),
]
